------------------------------------------------------------
-- Database table removal script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- note: spaces within table names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- Use this script to drop the tables created by -
--   'C:\Users\c7353785\OneDrive - Leeds Beckett University\admission.sql'

-- Dropping a table has the effect of removing it from the Database.  All existing data is lost
-- as well as the definition of the table itself (stored as meta-data).  Dropping the tables allows
-- them to be re-created within the Database, even if they already exist.


--------------------------------------------------------------

-- Drop tables --

DROP TABLE CareHome_Time_Dim CASCADE CONSTRAINTS;

DROP TABLE CareHome_Location_Dim CASCADE CONSTRAINTS;

DROP TABLE CareHome_Admission_Fact CASCADE CONSTRAINTS;


--------------------------------------------------------------
-- End of DDL DROP file auto-generation
--------------------------------------------------------------

--------------------------------------------------------------
-- Database creation Script

-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.

-- Verbose generation: ON

-- note: spaces within table/column names have been replaced by underscores (_)

-- Target DB: SQL2

-- Entity Model :Entity Relationship Diagram

-- To drop the tables generated by this script run -
--   'C:\Users\c7353785\OneDrive - Leeds Beckett University\admission_drop.sql'

--------------------------------------------------------------



--------------------------------------------------------------
-- Table Creation --

-- Each entity on the model is represented by a table that needs to be created within the Database.
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.

-- Create a Database table to represent the "Time_Dim" entity.
CREATE TABLE CareHome_Time_Dim(
	Time_ID	INTEGER NOT NULL,
	Year	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "Time_Dim".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_Time_Dim PRIMARY KEY (Time_ID)
);

-- Create a Database table to represent the "CareHome_Location_Dim" entity.
CREATE TABLE CareHome_Location_Dim(
	CareHome_NO	INTEGER NOT NULL,
    CARE_HOME_ID INTEGER,
    CARE_CENTRE_NAME VARCHAR(20),
    PREVIOUS_CARE_CENTRE_NAME VARCHAR(20),
	CareHome_Location	VARCHAR(20),
	-- Specify the PRIMARY KEY constraint for table "CareHome_Location_Dim".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_CareHome_Location_Dim PRIMARY KEY (CareHome_NO)
);

-- Create a Database table to represent the "Admission_Fact" entity.
CREATE TABLE CareHome_Admission_Fact(
	Admission_Fact_ID	INTEGER NOT NULL,
	fk1_Time_ID	INTEGER NOT NULL,
	fk2_CareHome_NO	INTEGER NOT NULL,
    No_Of_Admissions	INTEGER,
	-- Specify the PRIMARY KEY constraint for table "Admission_Fact".
	-- This indicates which attribute(s) uniquely identify each row of data.
	CONSTRAINT	pk_Admission_Fact PRIMARY KEY (Admission_Fact_ID)
);


--------------------------------------------------------------
-- Alter Tables to add fk constraints --

-- Now all the tables have been created the ALTER TABLE command is used to define some additional
-- constraints.  These typically constrain values of foreign keys to be associated in some way
-- with the primary keys of related tables.  Foreign key constraints can actually be specified
-- when each table is created, but doing so can lead to dependency problems within the script
-- i.e. tables may be referenced before they have been created.  This method is therefore safer.

-- Alter table to add new constraints required to implement the "Admission_Fact_Time_Dim" relationship

-- This constraint ensures that the foreign key of table "Admission_Fact"
-- correctly references the primary key of table "Time_Dim"

ALTER TABLE CareHome_Admission_Fact ADD CONSTRAINT fk1_Admission_Fact_to_Time_Dim FOREIGN KEY(fk1_Time_ID) REFERENCES CareHome_Time_Dim(Time_ID);

-- Alter table to add new constraints required to implement the "Admission_Fact_CareHome_Location_Dim" relationship

-- This constraint ensures that the foreign key of table "Admission_Fact"
-- correctly references the primary key of table "CareHome_Location_Dim"

ALTER TABLE CareHome_Admission_Fact ADD CONSTRAINT fk2_Admission_Fact_to_CareHome_Location_Dim FOREIGN KEY(fk2_CareHome_NO) REFERENCES CareHome_Location_Dim(CareHome_NO);


--------------------------------------------------------------
-- End of DDL file auto-generation
--------------------------------------------------------------
