-- MERGE SOURCE WYR AND NYR
DROP TABLE CAREHOME_STAGEAREA1;

CREATE TABLE CAREHOME_STAGEAREA1(
    ADMISSION_YEAR  INTEGER,
    CARE_HOME_ID INTEGER,
    CARE_CENTRE_NAME    VARCHAR(50),
    TOWN VARCHAR(50),
    TOTAL_ADMISSIONS INTEGER,
    SOURCE_DATASET VARCHAR(10)
);

INSERT INTO  CAREHOME_STAGEAREA1 (SELECT ADMISSION_YEAR, CARE_ID, CARE_CENTRE_NAME, TOWN, TOTAL_ADMISSIONS, 'WYR' FROM WYR_DATASET1);

INSERT INTO  CAREHOME_STAGEAREA1 (SELECT ADMISSION_YEAR, CARE_CENTRE_ID, CARE_CENTRE_NAME, TOWN, TOTAL_ADMISSIONS, 'NYR' FROM NYR_DATASET2);

--CREATE TABLE CAREHOME_STAGEAREA1 AS SELECT ADMISSION_YEAR, CARE_CENTRE_NAME, TOWN, TOTAL_ADMISSIONS FROM WYR_DATASET1;

--INSERT INTO  CAREHOME_STAGEAREA1 (SELECT ADMISSION_YEAR, CARE_CENTRE_NAME, TOWN, TOTAL_ADMISSIONS FROM NYR_DATASET2);

-- TRANSFORM
-- Data Quality checks and transformation on S1_STAGEAREA
-- Quality Check example -	Update the data, maybe set it to ‘not known’, or maybe delete it?
-- This is the code we want to do - don't run it just yet
--UPDATE CAREHOME_STAGEAREA1
--SET ADMISSION_YEAR = ''
--WHERE 
--ADMISSION_YEAR IS NULL
--OR ADMISSION_YEAR = ''
--OR ADMISSION_YEAR = '-';

-- Transformation (or Quality Check?)

UPDATE CAREHOME_STAGEAREA1 SET TOWN = 'Wakefield' WHERE TOWN ='WAKEFIELD';

-- TEMPERARY TABLE TO STORE DISTINCT YEAR

DROP table CAREHOME_TIME_DIM_TEMP;
Create table CAREHOME_TIME_DIM_TEMP as SELECT DISTINCT ADMISSION_YEAR FROM CAREHOME_STAGEAREA1;

-- SEQUENCE FOR TIME TABLE
DROP sequence time_seq;
create sequence time_SEQ
start with 1
increment by 1
maxvalue 10000
minvalue 1;

-- CARE HOME TIME DIMENSION TABLE
INSERT INTO CAREHOME_TIME_DIM SELECT time_seq.nextval, ADMISSION_YEAR FROM CAREHOME_TIME_DIM_TEMP;


DROP table CAREHOME_LOCATION_DIM_TEMP;
Create table CAREHOME_LOCATION_DIM_TEMP as SELECT DISTINCT  CARE_CENTRE_NAME, TOWN, CARE_HOME_ID FROM CAREHOME_STAGEAREA1;

-- SEQUENCE FOR LOCATION DIMENSION
DROP sequence loc_seq;
create sequence loc_SEQ
start with 1
increment by 1
maxvalue 10000
minvalue 1;

-- CARE HOME LOCATION DIMENSION TABLE
INSERT INTO CAREHOME_LOCATION_DIM SELECT loc_seq.nextval, CARE_HOME_ID, CARE_CENTRE_NAME, NULL, TOWN 
FROM CAREHOME_LOCATION_DIM_TEMP;

-- SEQUENCE FOR FACT TABLE
DROP sequence fact_seq;
create sequence FACT_SEQ
start with 1
increment by 1
maxvalue 10000
minvalue 1;

-- TEMPERARY TABLE TO STORE ALL THE DATA FROM THE STAGING AGE AND THE CALCULATION OF MEASURE OF FACT TABLE
DROP table CAREHOME_ADMISSION_FACT_TMP CASCADE CONSTRAINTS;
CREATE TABLE CAREHOME_ADMISSION_FACT_TMP AS
SELECT ADMISSION_YEAR as which_year, CARE_HOME_ID, CARE_CENTRE_NAME, TOWN, SUM(TOTAL_ADMISSIONS) as ADMISSIONS FROM CAREHOME_STAGEAREA1
GROUP BY ADMISSION_YEAR, CARE_HOME_ID, CARE_CENTRE_NAME, TOWN;

-- CARE HOME FACT TABLE
INSERT INTO CAREHOME_ADMISSION_FACT(ADMISSION_FACT_ID, FK1_TIME_ID, FK2_CAREHOME_NO , NO_OF_ADMISSIONS)
SELECT fact_seq.nextval,  CAREHOME_TIME_DIM.TIME_ID, CAREHOME_LOCATION_DIM.CareHome_NO, CAREHOME_ADMISSION_FACT_TMP.ADMISSIONS
FROM CAREHOME_TIME_DIM, CAREHOME_LOCATION_DIM, CAREHOME_ADMISSION_FACT_TMP
WHERE CAREHOME_ADMISSION_FACT_TMP.CARE_HOME_ID = CAREHOME_LOCATION_DIM.CARE_HOME_ID AND CAREHOME_ADMISSION_FACT_TMP.CARE_CENTRE_NAME = CAREHOME_LOCATION_DIM.CARE_CENTRE_NAME AND CAREHOME_ADMISSION_FACT_TMP.TOWN = CAREHOME_LOCATION_DIM.CAREHOME_LOCATION AND CAREHOME_ADMISSION_FACT_TMP.WHICH_YEAR = CAREHOME_TIME_DIM.YEAR;

--Slowly changing dimension for WYR source
MERGE into CAREHOME_LOCATION_DIM cc 
using (select * from WYR_CARE_CENTRE) wyr
 on (cc.CARE_HOME_ID = wyr.CARE_ID)  
WHEN MATCHED THEN 
  UPDATE
  SET cc.PREVIOUS_CARE_CENTRE_NAME = cc.CARE_CENTRE_NAME, cc.CARE_CENTRE_NAME = wyr.CARE_CENTRE_NAME WHERE wyr.CARE_CENTRE_NAME <> cc.CARE_CENTRE_NAME;

--Slowly changing dimension for NYR source
MERGE into CAREHOME_LOCATION_DIM cc 
using (select * from NYR_CARE_CENTRE) nyr
 on (cc.CARE_HOME_ID = nyr.CARE_CENTRE_ID)  
WHEN MATCHED THEN 
  UPDATE
  SET cc.PREVIOUS_CARE_CENTRE_NAME = cc.CARE_CENTRE_NAME, cc.CARE_CENTRE_NAME = nyr.CARE_CENTRE_NAME WHERE nyr.CARE_CENTRE_NAME <> cc.CARE_CENTRE_NAME;
  

  
  SELECT * FROM CAREHOME_LOCATION_DIM;

