--for extracting source one data
DROP TABLE WYR_DATASET1;

CREATE TABLE WYR_DATASET1 AS
SELECT
    cc.CARE_ID,	
    EXTRACT(YEAR FROM r.ADMISSION_DATE) AS admission_year,
    cc.CARE_CENTRE_NAME, cc.TOWN,
    COUNT(*) AS total_admissions
FROM
    WYR_RESERVATION r
JOIN WYR_BEDASSIGNED b ON b.RESERVATION_ID = r.RESERVATION_ID
JOIN WYR_BED d ON d.BED_NO = b.BED_NO
JOIN WYR_WARD w ON w.WARD_NO = d.WARD_NO
JOIN WYR_CARE_CENTRE cc ON cc.CARE_ID = w.CARE_ID
WHERE RESERVATION_STATUS != 'Cancelled'
GROUP BY
    EXTRACT(YEAR FROM r.ADMISSION_DATE), cc.CARE_ID, cc.CARE_CENTRE_NAME, cc.TOWN
ORDER BY
    EXTRACT(YEAR FROM r.ADMISSION_DATE), cc.CARE_ID, cc.CARE_CENTRE_NAME, cc.TOWN;

DROP TABLE NYR_DATASET2;

--Extracting source two data
CREATE TABLE NYR_DATASET2 AS
SELECT
    cc.CARE_CENTRE_ID,
    EXTRACT(YEAR FROM r.ADMISSION_DATE) AS admission_year,
    cc.CARE_CENTRE_NAME, cc.TOWN,
    COUNT(*) AS total_admissions
FROM
    NYR_ADMISSION r
JOIN NYR_BED d ON d.BED_ID = r.BED_ID
JOIN NYR_WARD w ON w.WARD_ID = d.WARD_ID
JOIN NYR_CARE_CENTRE cc ON cc.CARE_CENTRE_ID = w.CARE_CENTRE_ID
WHERE ADMISSION_STATUS != 'CANCELLED'
GROUP BY
    EXTRACT(YEAR FROM r.ADMISSION_DATE), cc.CARE_CENTRE_ID, cc.CARE_CENTRE_NAME, cc.TOWN
ORDER BY
    EXTRACT(YEAR FROM r.ADMISSION_DATE), cc.CARE_CENTRE_ID, cc.CARE_CENTRE_NAME, cc.TOWN;
